# Generated by Django 5.2.1 on 2025-05-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_item_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='amount_off',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='percent_off',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
