# Generated by Django 5.2.1 on 2025-05-28 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_discount_amount_off_discount_percent_off'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='id',
            new_name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='disc',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.discount'),
        ),
    ]
